server:
  port: 8084

spring:
  application:
    name: certificate-service
  datasource:
    url: jdbc:postgresql://localhost:5432/civicpulse_db
    username: postgres
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/civicpulse
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

app:
  upload:
    certificate-docs: C:/Project/uploads/certificate-docs
certificate:
  pdf:
    output-path: C:/Project/uploads/certificates    