global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:9000']
    metrics_path: '/actuator/prometheus'

  - job_name: 'citizen-service'
    static_configs:
      - targets: ['citizen-service:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'grievance-service'
    static_configs:
      - targets: ['grievance-service:8083']
    metrics_path: '/actuator/prometheus'

  - job_name: 'certificate-service'
    static_configs:
      - targets: ['certificate-service:8084']
    metrics_path: '/actuator/prometheus'

  - job_name: 'welfare-service'
    static_configs:
      - targets: ['welfare-service:8085']
    metrics_path: '/actuator/prometheus'

  - job_name: 'reporting-service'
    static_configs:
      - targets: ['reporting-service:8086']
    metrics_path: '/actuator/prometheus'