spring:
  application:
    name: welfare-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/civicpulse_db
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/civicpulse
          jwk-set-uri: http://localhost:8080/realms/civicpulse/protocol/openid-connect/certs
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
    consumer:
      bootstrap-servers: localhost:9092
      group-id: welfare-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
    properties:
      spring.json.use.type.headers: false

server:
  port: 8085
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    com.civicpulse.welfareservice: DEBUG
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

keycloak:
  admin:
    server-url: http://localhost:8080
    target-realm: civicpulse
    citizen-role: CITIZEN
    client-secret: jN2aoubARsn0k9sdqRumX7Mxb4CJ2NMY

app:
  upload:
    welfare-docs: C:\Project\uploads\welfare-docs